import React from 'react';
import { useBusiness } from '../context/BusinessContext';
import { Megaphone, Globe, CheckCircle2 } from 'lucide-react';

export default function MarketInsights() {
  const { customAnalytics } = useBusiness();

  if (!customAnalytics) return <div className="p-8"><h1 className="text-2xl text-white">Market Insights</h1><p className="text-slate-400">Upload business data to analyze market positioning.</p></div>;

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div>
         <h1 className="text-3xl font-bold font-syne text-white mb-2">Market & Growth Strategies</h1>
         <p className="text-slate-400">Tactical blueprints generated by AI exclusively for your data.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {customAnalytics.strategies && customAnalytics.strategies.map((strat: string, i: number) => (
          <div key={i} className="bg-[#12121A] border border-[#2A2A3A] p-6 rounded-2xl hover:border-blue-500/50 transition-colors">
            <h3 className="flex items-center gap-2 text-blue-400 font-bold mb-4">
              <span className="w-6 h-6 rounded bg-blue-500/20 flex items-center justify-center text-xs">{i+1}</span>
              Strategy Blueprint
            </h3>
            <p className="text-slate-300 leading-relaxed text-sm">{strat}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
